### ISSUE TITLE
Invisible characters in the PreText element

### ISSUE THREAD

**Issue by bfintal** [GetmeUK/ContentTools#263]
Checking the code, PreText adds `&#8203;` or `\u200B` on the end of the element. And some of these get left behind inside the PreText in certain scenarios.

This is minor though, no major effects except that when you encounter this invisible character you'll have to press double delete to remove it.

How to replicate:

1. Create an empty PreText element.
2. Type "a" (just 1 character)
3. Hit the enter key
4. Type "a" again
5. Press up, then down
6. Hit the enter key
7. Type "a"

Open your browser inspector and you should see `&#8203;` in the element. This is what I'm getting:

    a
    &#8203;a&#8203;

**Comment by anthonyjb** [comment]
The character is there intentionally so there presences isn't a bug during editing, without it pressing return at the end of a `pre` element doesn't generate a new line consistently and prevents you from moving in and out of the element consistently with the arrow keys.

I've noticed that I sometimes they get left in content when saved also but haven't found a consistent way to replicate, do you have one?

**Comment by bfintal** [comment]
The steps I enumerated above works in the sandbox / demo :)

**Comment by bfintal** [comment]
In:

    PreText.prototype._onKeyUp

I think this should fix it:

    //html = html.replace(/\u200B$/g, '');
    html = html.replace(/\u200B/g, '');

**Comment by anthonyjb** [comment]
@bfintal thanks for the suggestions but unfortunately this doesn't resolve it :/ Will keep looking at it now though.

**Comment by anthonyjb** [comment]
I've pushed a fix for this that for me resolves the issue for the steps you've provided to produce it - let me know how you get on.

You will still see a zero-width-space (\u200B) at the end of the content of a `PreText`, but it wont be present when you save the HTML out and doesn't impact the user's ability to edit the content.
