### ISSUE TITLE
IE11 - editable field -> paste function

### ISSUE THREAD

**Issue by kure-** [GetmeUK/ContentTools#339]
I'm having a troubles with IE11 which sometimes on some editable fields does not paste data (text) from clipboard to the field. From what I have experienced, clicking out of the field, clicking back and then pasting the data works. I'm using keyboard combo with "ctrl + v".

I'm initating the editor and then calling the editor on fields with data attribute. Everything seems to be working properly except the Paste event.
`<div class="SomeClass" data-field data-strip data-editable data-required data-name="some_field">
	<p>SomeValue</p>
</div>`

Some data-attributes are used for save callback and shouldnt be related.

Everything works in browsers, but not in application Internet Explorer 11 (havent checked other versions/Edge)

Edit: i'm using version 1.30,0., updated from 1.27.0. where I have experienced the same.

**Comment by kure-** [comment]
Note: it is probably IE11 related since it may lose focus when focusing contenteditable area

**Comment by kure-** [comment]
Note: every even clicked editable element works with pasting the data via ctrl + v in IE11. Every odd does not work, unless you click twice:
http://getcontenttools.com/demo

**Comment by anthonyjb** [comment]
Hi @kure- thanks for reporting this - I don't have access to IE directly but will take a look through the code to see if I can see anything obvious that might cause this and try to try it out on IE Edge tomorrow to see if the problem exists in other versions.

**Comment by kure-** [comment]
any update in here?:)
thanks

**Comment by anthonyjb** [comment]
Hi @kure- I have confirmed I'm also seeing this issue - I haven't yet identified if it's an issue with CT or IE yet though, will let you know when I've figured that out.

**Comment by kure-** [comment]
Is there eventually any quick fix? I have a users who can use just IE/Edge and they're using the editor on daily basis with certain amount of data being transfered from other sources via the editor, which makes the editor not usable right now :)

**Comment by anthonyjb** [comment]
@kure- this is an issue in the latest version of IE as far as I can tell also, I have no idea what causes it as of yet, but it seems that on some editable content divisions the browser doesn't set the selection/carat when you click it (which prevents the paste).

Rather than being specific to odd elements (vs. even), I have found that the behaviour is specific to odd focus events, so for example the first editable element you click on will not let you select it, but the next one will, if you then select a different element (which wont work) then select the first element you clicked on that will now work.

I want to try resending the click event to the element once it has been set to `contenteditable` to see if that helps so I'll look at that next. As I say I don't have access to run IE on my machine (only over browserstack) so it's a pain to test things against but I will look at this further over the next couple of days.

If someone with IE and the time can look at this and provide any additional insights I'd be grateful.

**Comment by anthonyjb** [comment]
@kure- just following up on this, if I just have a number contenteditable elements on the page then IE does have an issue with single click selection on all of them so it must be the way the ContentTools/Edit is converting an element to editable.

Looking into solutions currently.

**Comment by anthonyjb** [comment]
@kure- OK I have a solution I believe so intend to post in the next release (hopefully in the next couple of hours).

**Comment by anthonyjb** [comment]
Fixed in [release 1.3.1](https://github.com/GetmeUK/ContentTools/releases/tag/1.3.1).

**Comment by kure-** [comment]
Hi there, there seem to be still an issue with this, once element is nested. E.g. ul > li and pasting to it.  E.g. http://getcontenttools.com/demo  > About content tools

**Comment by anthonyjb** [comment]
@kure - Might be that for nested elements there's a further issue, I'll take a look confirm and re-open the issue.
